#!/bin/bash
# 
# Upgrade OwnCloud
# This is not really a script, but these are instructions to be followed manually.
# https://doc.owncloud.org/server/latest/admin_manual/maintenance/update.html

NEW_VERSION=10.2.1
APPS=( activity files_pdfviewer files_texteditor gallery )

cd /var/www/html/owncloud/
sudo -u www-data ./occ maintenance:mode --on
sudo service apache2 stop
for i in "${APPS[@]}"; do sudo -u www-data ./occ app:disable $i; done
wget -qO- https://download.owncloud.org/community/owncloud-${NEW_VERSION}.tar.bz2 | tar --transform 's/^owncloud/owncloud-${NEW_VERSION}/' -jxv -C /var/www/html/
cp -av /var/www/html/owncloud{,-${NEW_VERSION}}/config/config.php
# use hard links to avoid duplicating space
cp -avl /var/www/html/owncloud{,-${NEW_VERSION}}/data/
cd ..
mv owncloud{,-old}
mv owncloud{-${NEW_VERSION},}
cd owncloud
sudo -u www-data ./occ upgrade
# The following is a local copy of the script at https://doc.owncloud.org/server/10.2/admin_manual/installation/installation_wizard.html#post-installation-steps
# Actually, its latest version also includes some of these upgrade steps.
# Therefore it's best to run selected parts of that script manually.
~/bin/owncloud-permissions
sudo -u www-data ./occ maintenance:mode --off
for i in "${APPS[@]}"; do sudo -u www-data ./occ app:enable $i; done
sudo -u www-data ./occ maintenance:update:htaccess
cd ..
# diff -r --brief owncloud owncloud-old/
sudo service apache2 start
rm -rf owncloud-old
# https://doc.owncloud.org/server/10.0/admin_manual/maintenance/update.html#setting-permissions-for-updating
# https://doc.owncloud.org/server/9.0/admin_manual/configuration_server/index_php_less_urls.html
