#!/bin/bash
# 
# tmuxp-launcher: load a tmuxp session from all available profiles
# 
# © Christoph Lange <math.semantic.web@gmail.com> 2021

DIRECTORY="$HOME/.tmuxp"

# choose a tmux session
exec 3>&1
choice=$(dialog --backtitle "Project" --menu "Select the project for which a tmux session will be created:" 15 40 10 \
                $(cd "$DIRECTORY"
                  let i=1
                  for file in *.yaml
                  do
                      session="${file%.yaml}"
                      echo -n "${session} $((i++)) "
                  done
                ) 2>&1 1>&3)
exec 3>&-
clear

# SSH public key setup

# As I'm a non-admin user on Windows and cannot run the Windows OpenSSH Service, I need Cygwin's OpenSSH, and thus need to prioritize Cygwin's path
PATH="/usr/bin:$PATH"

if ! pgrep -x ssh-agent
then
    if eval `ssh-agent` && ssh-add ~/.ssh/id_ed25519
    then
        setx SSH_AUTH_SOCK $SSH_AUTH_SOCK
        setx SSH_AGENT_PID $SSH_AGENT_PID
    fi
fi

# start the tmux session
cd "$DIRECTORY"
exec tmuxp load "$choice.yaml"
