#!/bin/bash
# 
# qpdf-concat-even: concatenate multiple PDF documents, such that each one starts on an even page of the merged document (for double-sided printing)
#
# Usage: qpdf-concat-even INPUT... OUTPUT
# 
# © Christoph Lange <math.semantic.web@gmail.com> 2022

if (($# < 2))
then
   echo "At least one input file and the output file must be specified." >&2
   exit 1
fi

# idea: https://unix.stackexchange.com/a/511804
command=(qpdf --empty --pages)
npages=0
while (($# >= 2))
do
    # insert blank page if previous document had an odd number of pages
    (( npages % 2 )) && command+=(blank.pdf)
    # TODO make sure the blank-page PDF exists (in the desired size)
    # echo showpage | ps2pdf -sPAPERSIZE=letter - blank.pdf
# echo showpage | ps2pdf -dDEVICEWIDTHPOINTS=595 -dDEVICEHEIGHTPOINTS=842 -  foo.pdf
# pdfinfo foo.pdf                         Producer:       GPL Ghostscript 9.53.3
# CreationDate:   Fri May 27 22:08:08 2022 CEST
# ModDate:        Fri May 27 22:08:08 2022 CEST
# Tagged:         no
# UserProperties: no
# Suspects:       no
# Form:           none
# JavaScript:     no
# Pages:          1
# Encrypted:      no
# Page size:      595 x 842 pts (A4)
# Page rot:       0
# File size:      2326 bytes
# Optimized:      no
# PDF version:    1.4
    # https://unix.stackexchange.com/questions/277892/how-do-i-create-a-blank-pdf-from-the-command-line
    command+=("$1")
    npages=$(qpdf --show-npages "$1")
    shift
done
command+=(-- "$1")
echo "${command[@]}"
